// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlUvKAklwemdchGJUNUTBtHNX_v5MQNH4',
    appId: '1:1015673634339:web:cf5c175f49d850e6233b96',
    messagingSenderId: '1015673634339',
    projectId: 'fir-practice-16ae7',
    authDomain: 'fir-practice-16ae7.firebaseapp.com',
    storageBucket: 'fir-practice-16ae7.appspot.com',
    measurementId: 'G-K9113WQ3NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt91x5JkV2jwWsyeS_p2-TelalvCyZYxs',
    appId: '1:1015673634339:android:0ec6dcf0825470f8233b96',
    messagingSenderId: '1015673634339',
    projectId: 'fir-practice-16ae7',
    storageBucket: 'fir-practice-16ae7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGkmO-FYynWvwIp2RaqRiyprdgJbrt8E0',
    appId: '1:1015673634339:ios:3052d9a516611967233b96',
    messagingSenderId: '1015673634339',
    projectId: 'fir-practice-16ae7',
    storageBucket: 'fir-practice-16ae7.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGkmO-FYynWvwIp2RaqRiyprdgJbrt8E0',
    appId: '1:1015673634339:ios:ed8c7f00b5e2cffd233b96',
    messagingSenderId: '1015673634339',
    projectId: 'fir-practice-16ae7',
    storageBucket: 'fir-practice-16ae7.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
